import crypto from 'node:crypto';
import type { AdCampaign } from './ad-campaigns.js';
import type { BrandCampaign } from './brand-campaigns.js';
import { daysInRangeInclusive, toISODate } from './date-range.js';
import { fromAgorot, roundMoney } from './money.js';
import { boostFeePercent } from './pricing.js';
import { store } from '../config/store.config.js';

// Range-aware MOCK ad metrics (CURRENT_TASK.md → סשן ב׳). Deterministic — seeded
// per entity so numbers stay stable across reloads — and O(1) per entity (a
// seeded daily rate × the number of days in the range, NOT a per-day loop), so
// it scales to thousands of stores/campaigns without a per-day×per-entity blowup.
// Stands in for a real Google/Meta reporting API's date-range query until one is
// connected (see GO_LIVE_CHECKLIST.md). Nothing here moves money.

/**
 * **Is every number this module returns invented?** Today: yes.
 *
 * A dashboard may render a mock — the ad tabs are labelled as a preview and nobody files anything
 * from them. A DOCUMENT may not: the accounting statement goes to a רו״ח, and a line of income that
 * was generated by a hash function is a false statement wearing a total. So the statement asks this
 * flag rather than deciding for itself, and shows the ad-margin line as pending instead of as a
 * figure (`platform-statement.ts`, `admin-statement-load.ts`).
 *
 * **Flip it to `false` on the day a real Google/Meta reporting account is connected** (GO_LIVE §2),
 * in the same change that makes this module read that account — and `loadPlatformStatement` then
 * needs the campaign list it currently does not fetch. Both places name each other, so neither can
 * be flipped alone and quietly report the mock as fact.
 */
export const AD_METRICS_ARE_MOCK = true;

/** Deterministic 0..1 from a seed string. */
function frac(seed: string): number {
  return crypto.createHash('sha256').update(seed).digest().readUInt32BE(0) / 0xffffffff;
}

export interface RangeStat {
  impressions: number;
  clicks: number;
  ctr: number;
  /** What the SELLER is charged — the figure his budget cap is a ceiling on. */
  spend: number;
  /** What of that reached Google/Meta. The platform's management fee is the difference: the fee
   *  comes OUT of the budget (owner's decision, 2026-07-30), so a 500₪ cap buys 500₪ minus the
   *  fee worth of advertising rather than 500₪ of ads plus a bill on top. Kept as its own field
   *  because the two are different money: `spend` is the seller's cost, `adSpend` is the
   *  platform's pass-through to the ad network, and only their difference is income. */
  adSpend: number;
  cpc: number;
  /** Sales ATTRIBUTED to the campaign, and the word is doing real work — the seller reads this
   *  number as "how many orders did this ad bring me" and it is not that (user asked exactly this,
   *  CURRENT_TASK.md item 4). The rule the real integration must report under, so the mock and the
   *  glossary the seller reads can never mean different things:
   *
   *  - **Click-through with a lookback window, not "bought immediately".** A buyer who clicks the
   *    ad, leaves, and returns days later to buy IS counted — Google Ads' default window is 30
   *    days from the click, Meta's is 7-day-click (+1-day-view). Whether he added to cart on the
   *    first visit is irrelevant: the click is the attributed event, the purchase only has to land
   *    inside the window.
   *  - **It cannot be exact, and that is not a bug we can fix here.** A click on a phone and a
   *    purchase on a desktop, a cleared cookie or an ad-blocker all break the join; both networks
   *    fill those gaps with MODELLED conversions. Two networks can also each claim the same sale,
   *    so summing campaigns can exceed the store's real order count.
   *  - **The only deterministic version is first-party, and the CAPTURE half of it now exists**
   *    (`lib/attribution.ts`, migration 0010, 2026-08-04): the click id and UTM tags come off the
   *    landing URL into a first-party cookie and are stamped on every order at checkout. What is
   *    still missing is the report that reads them, which is part of the real integration — so
   *    nothing in this module consumes `orders.attribution` yet, on purpose. Until real ad accounts
   *    exist no link carries those parameters, and a true 0 beside these mock thousands would be
   *    worse than either number alone. Scope for the remaining half: `GO_LIVE_CHECKLIST.md` §2.5.
   *
   *  Until that report is built the seller-facing label says "משוער"/"(est.)" and the glossary
   *  states the window — the honest framing the user asked for, not a precision we do not have.
   *  **Both change together with the report, never before it.** */
  conversions: number;
  roas: number;
}
const ZERO: RangeStat = { impressions: 0, clicks: 0, ctr: 0, spend: 0, adSpend: 0, cpc: 0, conversions: 0, roas: 0 };

/** Cost per click from spend/clicks, guarded against divide-by-zero (₪, 2dp). */
function cpcOf(spend: number, clicks: number): number {
  return clicks > 0 ? roundMoney(spend / clicks) : 0;
}

/** Click-through rate % from impressions/clicks, guarded against divide-by-zero. */
function ctrOf(impressions: number, clicks: number): number {
  return impressions > 0 ? Math.round((clicks / impressions) * 1000) / 10 : 0;
}

/** Baseline (platform-funded) impressions a store accrues over the range — a
 *  seeded per-day rate × the range length. */
export function baselineImpressionsInRange(storeId: string, from: string, to: string): number {
  const perDay = 15 + frac('base:' + storeId) * 75; // ~15–90 impressions/day
  return Math.round(perDay * daysInRangeInclusive(from, to));
}

/** ISO date `days` after `iso` (local calendar, DST-safe via Date arithmetic). */
function addDaysISO(iso: string, days: number): string {
  const [y, m, d] = iso.split('-').map(Number);
  const dt = new Date(y ?? 1970, (m ?? 1) - 1, d ?? 1);
  dt.setDate(dt.getDate() + days);
  return toISODate(dt);
}

/** The minimal shape a campaign needs for run-period math — shared by boost
 *  (AdCampaign) and brand (BrandCampaign) campaigns so both freeze on pause. */
interface Runnable {
  status: 'active' | 'paused';
  createdAt: string;
  updatedAt: string;
  pausedAt?: string;
  durationDays?: number;
}

/** A campaign's real run period — the window over which it actually accrued
 *  exposure. It starts when it was created and ENDS at whichever comes first:
 *  the day it was paused (frozen there — pausing stops future spend but never
 *  erases what already ran, CURRENT_TASK.md item 1), the end of its fixed
 *  duration, or `todayISO`. A paused campaign without an explicit `pausedAt`
 *  (legacy rows) falls back to `updatedAt`. */
function runPeriod(c: Runnable, todayISO: string): { start: string; end: string } {
  const start = c.createdAt.slice(0, 10);
  let end = todayISO;
  if (c.status === 'paused') {
    const pausedISO = (c.pausedAt ?? c.updatedAt).slice(0, 10);
    if (pausedISO < end) end = pausedISO;
  }
  if (c.durationDays) {
    const durEnd = addDaysISO(start, c.durationDays - 1);
    if (durEnd < end) end = durEnd;
  }
  if (end < start) end = start;
  return { start, end };
}

/** Active days of the campaign's run period that fall inside the window [from,to].
 *  Zero when the window lies entirely before launch or after it stopped. */
function overlapDays(c: Runnable, from: string, to: string): number {
  const { start, end } = runPeriod(c, to);
  const s = start > from ? start : from;
  const e = end < to ? end : to;
  return s > e ? 0 : daysInRangeInclusive(s, e);
}

/** What a campaign SPENDS over `days` — pacing times delivery, and neither half is optional.
 *
 *  Pacing: the divisor is the campaign's own period, NOT always 30. The form calls the figure a
 *  monthly cap for an ongoing boost and a TOTAL cap for a fixed 7/14/30-day one ("תקרת תקציב
 *  לקמפיין"). Dividing a 7-day 500₪ campaign by 30 paced it as if the 500 were monthly, so after
 *  running its whole week it reported ~117₪ — a fifth of what the seller had capped.
 *
 *  Delivery: a budget is a CEILING, never a commitment — Google and Meta charge for what the
 *  auction actually delivered, and a campaign that doesn't win enough impressions simply spends
 *  less. That is the normal outcome for a small budget in a narrow audience, and it is the whole
 *  point of the platform's own promise ("משלמים רק על הוצאה בפועל"). So a fully-run campaign
 *  lands NEAR its cap, not exactly on it: a seeded 82–98% utilisation, stable per campaign like
 *  every other number here. Pacing alone would have turned the ceiling into a guaranteed charge —
 *  a different product from the one the form describes.
 *
 *  Seeded separately from the campaign's CPM/CTR: one shared `rand` would tie "spent less" to
 *  "cheaper clicks", and those are independent in reality. */
function spendOver(campaign: { id: string; monthlyBudgetAgorot: number; durationDays?: number }, days: number): number {
  // **The one place a campaign budget crosses back out of agorot, and it has to be here.** The
  // stored cap is integer agorot (§7.7); every rate below it — CPM in ₪ per 1000 impressions, the
  // ₪90–260 basket value — is ILS, so feeding agorot straight in would price impressions off a
  // number a hundred times too large and report a campaign reaching a hundred times its audience.
  // Everything this module returns is ILS, which is what `platform-revenue.ts` documents at its
  // own boundary and converts once on the way in.
  const pace = fromAgorot(campaign.monthlyBudgetAgorot) / (campaign.durationDays ?? 30);
  const utilisation = 0.82 + frac('util:' + campaign.id) * 0.16;
  return pace * days * utilisation;
}

/** How much of a seller's charge actually buys advertising. The fee is a percentage OF THE AD
 *  SPEND and comes out of the budget (owner's decision, 2026-07-30) — so the charge is
 *  `adSpend × (1 + p)` and this inverts it. Reading the config through pricing.ts#boostFeePercent
 *  keeps this the same percentage the platform books as income and the same one the seller is
 *  shown in the budget tooltip. */
function adSpendOfCharge(charge: number): number {
  return charge / (1 + boostFeePercent(store.ads?.boostCommissionPercent) / 100);
}

/** Seeded, deterministic metrics for a campaign that ran `days` active days.
 *  Shared by the lifetime and windowed views so the two never disagree on rate. */
function accrue(campaign: AdCampaign, days: number): RangeStat {
  if (days <= 0) return ZERO;
  const rand = frac('camp:' + campaign.id);
  const spend = spendOver(campaign, days);
  // The management fee is taken OUT of the budget, so only the rest buys advertising — which
  // means the impressions have to be priced off THAT, not off what the seller was charged.
  // Deriving them from the charge would have quietly advertised money the platform kept.
  const adMoney = adSpendOfCharge(spend);
  const cpm = campaign.platform === 'google' ? 18 + rand * 14
    : campaign.platform === 'meta' ? 12 + rand * 10
    : 15 + rand * 12; // 'both' = blended Google+Meta band
  const imp = Math.round((adMoney / cpm) * 1000);
  const ctr = 1.2 + rand * 2.3; // %
  const clicks = Math.round(imp * (ctr / 100));
  const spendR = roundMoney(spend);
  // Sales attributed to the campaign — a seeded ~1.5%–5.5% of clicks convert.
  const conversions = Math.round(clicks * (0.015 + rand * 0.04));
  // ROAS is DERIVED from those sales, never seeded on its own. It used to be an independent
  // random band, so one card could read "0 מכירות" beside "x4.96 תשואה על הפרסום" — two figures
  // answering the same question and contradicting each other, which is exactly the number a
  // seller decides his next budget on. Revenue = sales × a seeded basket value, so zero sales
  // now honestly means zero return.
  const revenue = conversions * (90 + frac('aov:' + campaign.id) * 170); // ₪90–260 per order
  const roas = spendR > 0 ? roundMoney(revenue / spendR) : 0;
  return {
    impressions: imp, clicks, ctr: ctrOf(imp, clicks),
    spend: spendR, adSpend: roundMoney(adMoney),
    // Cost per click is what the CLICK cost the seller, not what the network charged for it —
    // the fee is part of what he paid for that click.
    cpc: cpcOf(spendR, clicks), conversions, roas,
  };
}

/** Metrics accrued during the overlap of the picked window [from,to] with the
 *  campaign's real run period. A paused campaign still reports the days it ran
 *  before it was paused (item 1) — it only reports ZERO for a window that lies
 *  entirely after it stopped, or entirely before it launched. */
export function campaignStatsInRange(campaign: AdCampaign, from: string, to: string): RangeStat {
  return accrue(campaign, overlapDays(campaign, from, to));
}

/** Lifetime ("since launch") totals — what this specific campaign has achieved
 *  over its whole run period, independent of any picked window (CURRENT_TASK.md
 *  item 3). This is the stable per-campaign headline; the window picker layers a
 *  recent-activity view on top of it. */
export function campaignLifetimeStats(campaign: AdCampaign, today: Date = new Date()): RangeStat {
  const { start, end } = runPeriod(campaign, toISODate(today));
  return accrue(campaign, daysInRangeInclusive(start, end));
}

/** Has a fixed-duration campaign already run its course? Derived, never stored: the end date is
 *  a pure function of createdAt + durationDays, so there is no second copy of it to go stale and
 *  no sweep needed to keep a status field honest. An ongoing campaign (no durationDays) never
 *  ends by itself — only the seller stops it. */
export function isCampaignEnded(campaign: AdCampaign, today: Date = new Date()): boolean {
  if (!campaign.durationDays) return false;
  const start = campaign.createdAt.slice(0, 10);
  return addDaysISO(start, campaign.durationDays - 1) < toISODate(today);
}

/** The campaign's run period as ISO dates + active-day count — for the card's
 *  "running since / ran X days" label. */
export function campaignRunPeriod(campaign: AdCampaign, today: Date = new Date()): { start: string; end: string; days: number } {
  const { start, end } = runPeriod(campaign, toISODate(today));
  return { start, end, days: daysInRangeInclusive(start, end) };
}

/** A campaign decorated with its mock stats for the chosen window (or lifetime
 *  totals when `range` is undefined) plus its run period — the exact response
 *  shape both the seller and admin ad-campaign routes return, kept here so they
 *  can't drift. */
export function withCampaignStats(campaign: AdCampaign, range?: { from: string; to: string }) {
  return {
    ...campaign,
    stats: range ? campaignStatsInRange(campaign, range.from, range.to) : campaignLifetimeStats(campaign),
    runPeriod: campaignRunPeriod(campaign),
    // Derived here so no card has to do date arithmetic to know which badge to draw: `ended` =
    // ran its full fixed duration, `archived` = it is history (cancelled, or ended and swept).
    ended: isCampaignEnded(campaign),
    archived: !!campaign.archivedAt,
  };
}

export function brandStatsInRange(campaign: BrandCampaign, from: string, to: string): RangeStat {
  const days = overlapDays(campaign, from, to);
  if (days === 0) return ZERO;
  const rand = frac('brand:' + campaign.id);
  const spend = spendOver(campaign, days);
  const cpm = campaign.platform === 'google' ? 10 + rand * 8 : 8 + rand * 7; // brand/awareness runs cheaper
  const impressions = (spend / cpm) * 1000;
  const ctr = 0.7 + rand * 1.6; // %
  const imp = Math.round(impressions);
  const clicks = Math.round(impressions * (ctr / 100));
  const spendR = roundMoney(spend);
  return {
    impressions: imp,
    clicks,
    ctr: ctrOf(imp, clicks),
    spend: spendR,
    // The platform's own ads: every shekel goes to the network, there is nobody to charge a fee.
    adSpend: spendR,
    cpc: cpcOf(spendR, clicks),
    conversions: Math.round(clicks * (0.02 + rand * 0.05)), // 2%–7% of clicks act
    roas: 0, // brand/awareness has no direct revenue attribution modelled
  };
}

export interface MockBrandStats {
  impressions: number;
  clicks: number;
  ctr: number;         // %
  spend: number;       // ILS
  conversions: number; // signups / new buyers attributed (awareness → action)
}

/**
 * A brand campaign's lifetime headline — what the admin card shows beside it.
 *
 * **Moved here from `brand-campaigns.ts` when that module went to Postgres.** It was the only
 * thing left in a data module that did money arithmetic and kept a second copy of the seeded-
 * fraction helper, which is how the two brand mocks were free to disagree on the same campaign.
 * They share `frac` now, so a campaign's numbers come from one seed wherever they are read.
 */
export function getMockBrandStats(campaign: BrandCampaign): MockBrandStats {
  if (campaign.status === 'paused') return { impressions: 0, clicks: 0, ctr: 0, spend: 0, conversions: 0 };

  const daysRunning = Math.max(1, Math.min(30, Math.floor((Date.now() - new Date(campaign.createdAt).getTime()) / 86400000) + 1));
  const spend = roundMoney((fromAgorot(campaign.monthlyBudgetAgorot) / 30) * daysRunning);

  const rand = frac('brand:' + campaign.id);
  // Brand/awareness ads run cheaper CPMs than shopping but convert less directly.
  const cpm = campaign.platform === 'google' ? 10 + rand * 8 : 8 + rand * 7;
  const impressions = Math.round((spend / cpm) * 1000);
  const ctr = Math.round((0.7 + rand * 1.6) * 1000) / 1000; // %, not money — a rate, so not roundMoney
  const clicks = Math.round(impressions * (ctr / 100));
  const conversions = Math.round(clicks * (0.02 + rand * 0.05)); // 2%–7% of clicks act

  return { impressions, clicks, ctr, spend, conversions };
}
