/**
 * GENERATED by scripts/generate-wordmark.mjs — do not hand-edit.
 * Run `npm run brand:wordmark` after changing anything it treats as authored
 * (the tracking, the thickening, the octagon's cut, the two optical ratios).
 *
 * The wordmark is OUTLINES, not text: Chakra Petch is not shipped to the browser
 * at all, so the logo cannot render in a fallback face and costs no font preload.
 * The generator's header explains why in full.
 *
 * Coordinates: 1000 units = 1em, x starts at the mark's left ink edge, y starts
 * at the ascender and the baseline is at y = 714.
 */

/** The drawn D — half a regular octagon, rebuilt against Chakra Petch 700. */
export const MARK_PATH =
  'M0 0 L358.874 0 L568 209.126 L568 504.874 L358.874 714 L0 714 Z M136 108.664 L293.727 108.664 L432 246.937 L432 467.063 L293.727 605.336 L136 605.336 Z';

/** "ezabin", outlined at -0.04em tracking. */
export const LETTERS_PATH =
  'M734 714L633 612L633 320L736 216L1017 216L1121 320L1121 509L765 509L765 573L797 606L960 606L990 575L990 549L1120 549L1120 614L1021 714L734 714M765 417L989 417L989 359L955 324L799 324L765 359L765 417M1146 714L1146 612L1423 325L1423 323L1156 323L1156 216L1594 216L1594 318L1317 605L1317 607L1594 607L1594 714L1146 714M1711 714L1619 622L1619 508L1711 416L1964 416L1964 353L1933 322L1783 322L1753 353L1753 381L1623 381L1623 324L1730 216L1987 216L2094 324L2094 714L1975 714L1975 643L1901 714L1711 714M1774 612L1892 612L1964 543L1964 510L1776 510L1749 537L1749 587L1774 612M2276 714L2169 606L2169 0L2301 0L2301 285L2374 216L2556 216L2659 320L2659 610L2556 714L2276 714M2339 602L2489 602L2527 563L2527 367L2489 328L2391 328L2301 418L2301 563L2339 602M2770 158L2724 112L2724 48L2770 2L2840 2L2886 48L2886 112L2840 158L2770 158M2739 714L2739 216L2871 216L2871 714L2739 714M2961 714L2961 216L3083 216L3083 299L3166 216L3327 216L3438 327L3438 714L3306 714L3306 363L3272 328L3188 328L3093 424L3093 714L2961 714';

/** The thickening, as a centred stroke in the coordinates above. Draw it with
 *  `paint-order="stroke"` and the SAME paint as the fill, on both the mark and
 *  the letters, or the two stop matching. */
export const STROKE_WIDTH = 14;

/** viewBox for the whole wordmark, tight to the stroked ink. */
export const VIEW_BOX = '-7 -7 3452 728';

/** viewBox for the mark on its own — the favicon, the menu row, a tile. */
export const MARK_VIEW_BOX = '-7 -7 582 728';

/** CSS height for the wordmark: everything else in the component is em, so this
 *  is the only size knob. It is the ascender plus the stroke. */
export const HEIGHT_EM = 0.728;

/** The lockup's ink width, in em of the wordmark's own font-size. */
export const INK_WIDTH_EM = 3.452;

/** The brand ramp, as ONE gradient across the whole wordmark. It must be
 *  `gradientUnits="userSpaceOnUse"`: the default resolves per element, which
 *  gives every letter its own full ramp and reads as pieces stuck together. */
export const GRADIENT = { from: '#2a3c40', to: '#3a5260', x1: 0, y1: 0, x2: 3438, y2: 714 };

/** The Hebrew line under the mark, which is still live Heebo text because it
 *  follows the visitor's language. `sizeEm` matches its ink width to the
 *  wordmark's; `marginEm` (in the tagline's OWN em) cancels Heebo's side
 *  bearing to the right of the מ, because a line box is not its ink and aligning
 *  the boxes parks the Hebrew a visible pixel inside the English.
 *  Both are re-solved by the generator whenever the wordmark moves — and
 *  `sizeEm` then carries a bisection against the built site, see the test. */
export const TAGLINE = { sizeEm: 0.40459, marginEm: -0.04607 };
