/**
 * GENERATED by scripts/generate-wordmark.mjs — do not hand-edit.
 * Run `npm run brand:wordmark` after changing anything it treats as authored
 * (the tracking, the thickening, the octagon's cut, the two optical ratios).
 *
 * The wordmark is OUTLINES, not text: Chakra Petch is not shipped to the browser
 * at all, so the logo cannot render in a fallback face and costs no font preload.
 * The generator's header explains why in full.
 *
 * Coordinates: 1000 units = 1em, x starts at the mark's left ink edge, y starts
 * at the ascender and the baseline is at y = 714.
 */

/** The drawn D — half a regular octagon, rebuilt against Chakra Petch 700. */
export const MARK_PATH =
  'M0 0 L358.874 0 L568 209.126 L568 504.874 L358.874 714 L0 714 Z M136 108.664 L293.727 108.664 L432 246.937 L432 467.063 L293.727 605.336 L136 605.336 Z';

/** "ezabin", outlined at -0.04em tracking, with every junction in the
 *  block — the mark's included — levelled to the same 55-unit ink gap. The
 *  levelling is a redistribution and cannot change the width; the generator's
 *  `EVEN_GAPS` says why the font's own spacing needed it. */
export const LETTERS_PATH =
  'M724 714L623 612L623 320L726 216L1007 216L1111 320L1111 509L755 509L755 573L787 606L950 606L980 575L980 549L1110 549L1110 614L1011 714L724 714M755 417L979 417L979 359L945 324L789 324L755 359L755 417M1166 714L1166 612L1443 325L1443 323L1176 323L1176 216L1614 216L1614 318L1337 605L1337 607L1614 607L1614 714L1166 714M1761 714L1669 622L1669 508L1761 416L2014 416L2014 353L1983 322L1833 322L1803 353L1803 381L1673 381L1673 324L1780 216L2037 216L2144 324L2144 714L2025 714L2025 643L1951 714L1761 714M1824 612L1942 612L2014 543L2014 510L1826 510L1799 537L1799 587L1824 612M2306 714L2199 606L2199 0L2331 0L2331 285L2404 216L2586 216L2689 320L2689 610L2586 714L2306 714M2369 602L2519 602L2557 563L2557 367L2519 328L2421 328L2331 418L2331 563L2369 602M2790 158L2744 112L2744 48L2790 2L2860 2L2906 48L2906 112L2860 158L2790 158M2759 714L2759 216L2891 216L2891 714L2759 714M2961 714L2961 216L3083 216L3083 299L3166 216L3327 216L3438 327L3438 714L3306 714L3306 363L3272 328L3188 328L3093 424L3093 714L2961 714';

/** The thickening, as a centred stroke in the coordinates above. Draw it with
 *  `paint-order="stroke"` and the SAME paint as the fill, on both the mark and
 *  the letters, or the two stop matching. */
export const STROKE_WIDTH = 14;

/** viewBox for the whole wordmark, tight to the stroked ink. */
export const VIEW_BOX = '-7 -7 3452 728';

/** viewBox for the mark on its own — the favicon, the menu row, a tile. */
export const MARK_VIEW_BOX = '-7 -7 582 728';

/** CSS height for the wordmark: everything else in the component is em, so this
 *  is the only size knob. It is the ascender plus the stroke. */
export const HEIGHT_EM = 0.728;

/** The lockup's ink width, in em of the wordmark's own font-size. */
export const INK_WIDTH_EM = 3.452;

/** The brand ramp, as ONE gradient across the whole wordmark. It must be
 *  `gradientUnits="userSpaceOnUse"`: the default resolves per element, which
 *  gives every letter its own full ramp and reads as pieces stuck together. */
export const GRADIENT = { from: '#2a3c40', to: '#3a5260', x1: 0, y1: 0, x2: 3438, y2: 714 };

/** The Hebrew line under the mark, which is still live Heebo text because it
 *  follows the visitor's language. `sizeEm` matches its ink width to the
 *  wordmark's; `marginEm` (in the tagline's OWN em) cancels Heebo's side
 *  bearing to the right of the מ, because a line box is not its ink and aligning
 *  the boxes parks the Hebrew a visible pixel inside the English.
 *  Both are re-solved by the generator whenever the wordmark moves — and
 *  `sizeEm` then carries a bisection against the built site, see the test.
 *
 *  `gapEm` is the space between the two lines, in the LOCKUP's em, so the site
 *  header and the mail header move together; a divergence there is a brand that
 *  looks assembled twice. It is authored rather than solved — see the
 *  generator. */
export const TAGLINE = { sizeEm: 0.40459, marginEm: -0.04607, gapEm: 0.12 };
