/**
 * The two things that turn a log row into something a person can act on: a code that says WHICH
 * failure this is, and a sentence that says WHAT it means.
 *
 * Both exist because of a workflow, not because of a schema. The mail arrives on a phone; the
 * dashboard is on a laptop; the fix happens in a conversation with somebody who was not there. Each
 * of those three needs the same failure named the same way, and a `uuid` in one place with nothing
 * in the other two is what makes that impossible.
 */

import { isMoneyPath, type ErrorSeverity } from './error-severity.js';

/**
 * A short code for one entry — `#a1b2c3d4`, the first eight characters of its uuid.
 *
 * **Why not the uuid.** Nobody reads out `4f8c2a1e-9b3d-4c7f-8e2a-1d6b9f3c8e4a`, nobody matches it
 * by eye against a screen, and nobody types it into a filter box. The code has to survive being
 * looked at on a phone and then found on a laptop, which is a constraint about human working
 * memory rather than about uniqueness.
 *
 * **Why not `seq`,** which is the natural incident number and is monotonic and short. It is
 * assigned by the database on insert, so it does not exist yet at the moment the alert mail is
 * built — and a code the mail cannot carry is not a code that links the mail to anything. The uuid
 * is generated by us, before the insert, which is exactly the property needed here.
 *
 * **Eight characters is enough because the table holds 500 rows.** That is 32 bits over a space of
 * five hundred; the chance any two live entries collide is on the order of one in ten million, and
 * the consequence of the collision is that a person looks at two rows instead of one. Both numbers
 * are fine. This is a lookup aid, never an identifier — nothing keys on it, and `setErrorResolved`
 * still takes the full uuid.
 */
export function errorRef(id: string): string {
  return `#${id.replace(/-/g, '').slice(0, 8)}`;
}

/**
 * What this failure MEANS, in the words someone would use to describe it to another person.
 *
 * The row already says `/api/checkout` and `500`, and between them they say everything except the
 * only thing that decides what happens next: whether a customer was hurt. "A buyer could not
 * complete a purchase" and "a page failed to render" are the same HTTP status and the same shape of
 * stack trace, and they are not the same event.
 *
 * Route-driven for the same reason `error-severity.ts` is: the route is a fact the server decided,
 * and the message is text that can carry request input. Every entry gets a sentence — an
 * unrecognised route falls back to the severity's own meaning rather than to nothing, because a
 * blank here would read as "we do not know what this is", which is a stronger claim than we mean.
 */
const MEANING_BY_PREFIX: readonly (readonly [string, string])[] = [
  ['/api/checkout', 'קונה לא הצליח להשלים רכישה'],
  ['/checkout', 'קונה נתקע בעמוד התשלום'],
  ['/api/payment', 'אישור התשלום מהספק נכשל — ייתכן שהזמנה חויבה ולא סומנה כשולמה'],
  ['/api/seller/orders', 'עדכון סטטוס הזמנה נכשל — ייתכן שמלאי לא הוחזר או שהקונה לא קיבל עדכון'],
  ['/api/cart', 'תקלה בעגלה'],
  ['/api/store-product', 'מוכר לא הצליח לשמור מוצר'],
  ['/api/store', 'מוכר לא הצליח לשמור הגדרות חנות'],
  ['/api/seller', 'תקלה בדשבורד המוכר'],
  ['/api/admin', 'תקלה בדשבורד הניהול'],
  ['/api/auth', 'תקלה בהתחברות'],
] as const;

const MEANING_BY_SEVERITY: Record<ErrorSeverity, string> = {
  critical: 'תקלה שעלולה לפגוע בכסף או במלאי',
  error: 'תקלה בשרת — הגולש לא קיבל את העמוד שביקש',
  warning: 'שגיאה שקרתה בדפדפן של גולש אחד',
};

export function errorMeaning(route: string | null | undefined, severity: ErrorSeverity | undefined): string {
  const level = severity ?? 'error';
  // The path only. A query string is caller-controlled, and it must not be able to change the
  // sentence a person reads about what happened — the same rule `isMoneyPath` follows.
  const path = (route ?? '').split('?')[0] ?? '';
  if (path) {
    for (const [prefix, meaning] of MEANING_BY_PREFIX) {
      if (path === prefix || path.startsWith(`${prefix}/`)) return meaning;
    }
  }
  // A critical entry on an unlisted route is the case worth being careful about: it means
  // `error-severity.ts` knows a money path that this file does not, which is a drift between two
  // lists that must never quietly read as "nothing special".
  if (level === 'critical' && !isMoneyPath(route)) return MEANING_BY_SEVERITY.critical;
  return MEANING_BY_SEVERITY[level];
}
