-- 0005_error_log_seq — arrival order for the error log, because a timestamp is not one.
--
-- The plan for this module said "no new migration": `error_log` already exists in 0001 and the
-- import already writes it. This column is here because a test written for the move FAILED and the
-- failure was real, not a fixture artifact.
--
-- The log was a JSON array, so its order was arrival order, for free. As a table it was
-- `ORDER BY created_at DESC, id` — and `created_at` is `now()`, whose resolution is finite:
-- measured in the test database, three entries written back to back land on the SAME millisecond.
-- The tie-break `id` is a random uuid, so within one instant the order is arbitrary. Two things
-- read that order and both are wrong when it is arbitrary:
--
--  1. The admin Alerts tab lists newest-first. Within a burst the list is shuffled — cosmetic, but
--     it is a triage screen, and "which came first" is what triage is.
--  2. **The 500-entry ceiling deletes by that order** (error-log.ts). "Oldest" decided by a random
--     uuid means a burst can evict an entry NEWER than one it keeps. And a burst is exactly when
--     the ceiling engages: a broken deploy fires hundreds of errors a second, all inside a few
--     ticks of the clock.
--
-- A sequence is the only tie-break that is actually arrival: monotonic, assigned by the database,
-- and independent of the clock and of how many instances are writing. `created_at` stays — it is
-- what a human reads and what `countSince` compares the "new since last opened" badge against —
-- but it stops being what the ordering rests on.
--
-- `bigint GENERATED BY DEFAULT AS IDENTITY` rather than `bigserial`: BY DEFAULT lets a writer
-- supply its own value where ALWAYS would refuse one, which is what keeps the import free to fix an
-- order later. On a database that already holds entries when this runs, Postgres backfills them in
-- physical order — for a table nothing updates that is insert order, which is the answer we want.
ALTER TABLE error_log ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- Both readers of the order — the newest-first page and the OFFSET the ceiling prunes by — are this
-- one index, which is also unique, so `ORDER BY seq DESC` never needs a second key.
CREATE UNIQUE INDEX error_log_seq_idx ON error_log (seq DESC);

-- `error_log_recent_idx (created_at DESC, id)` from 0001 no longer has a reader: nothing orders or
-- ranges by `created_at` any more. `error_log_open_idx` stays — the partial index on unresolved
-- entries is a different question and still the one a future "open alerts only" filter asks.
DROP INDEX error_log_recent_idx;
