-- When each seller-owned custom domain was last verified against the edge provider.
--
-- `custom_domain_status` was written only when a human pressed "check" in the dashboard
-- (`/api/store.ts`, action `check-custom-domain`). That made the record a snapshot of the last time
-- someone happened to look, and the application treats it as a fact: an 'active' domain is the
-- store's canonical, it is what platform surfaces link to, and every hit on the platform path 301s
-- to it. A seller who removes the CNAME at their registrar, lets the domain expire, or moves it to
-- another host therefore takes their own store offline — permanently, and silently, because nothing
-- re-reads the state that stopped being true. The custom-domain header promises the opposite ("the
-- store can never go offline if the custom domain's DNS/SSL lapses"), and without a re-check that
-- promise had no mechanism behind it.
--
-- The re-check is a job (`jobs/registry.ts` → custom-domain-check), and a job over an outbound API
-- must be BOUNDED and must ROTATE — one request per hostname to a server we do not control is the
-- shape that outlasts its own lease at scale (see feed-sync). This column is what makes the bound a
-- rotation instead of a cut-off: `ORDER BY custom_domain_checked_at ASC NULLS FIRST` puts the
-- longest-unchecked domain first, so a store that did not fit in one run leads the next one.
--
-- NULL means "never checked since this column existed" — true for every domain registered before
-- today, and deliberately first in line rather than assumed healthy.
--
-- Additive column, safe under the zero-downtime rule: the previous deploy neither reads nor writes
-- it, and no existing row needs backfilling.
ALTER TABLE stores ADD COLUMN IF NOT EXISTS custom_domain_checked_at timestamptz;
